### ISSUE TITLE
[Bug] rlp error

### ISSUE THREAD

**Issue by lazyanubis** [av1ctor/mo-evm-txs#1]
When I try to start a transaction and send it to the node, I encounter the following error:

(variant {err="wrong eth_sendRawTransaction result: {"jsonrpc":"2.0","id":2,"error":{"code":-32000,"message":"rlp: expected input list for types.AccessList, decoding into (types.DynamicFeeTx).AccessList"}}
"})

Transaction type: **EIP1559** and **EIP2930** (But **Legacy** is successful)

**Comment by av1ctor** [comment]
Do you have a project or code snippet to reproduce the error? I'm not sure if there's something wrong with the RLP library that's being used or if the problem is at this library. Thanks

**Comment by lazyanubis** [comment]
Just send a common EIP1559 signed transaction;

dfx canister call backend deploy_evm_contract '(vec{1:nat8}, 5:nat64, 100:nat64, 100:nat64, 100: nat64)'

parse result to hex text (return #ok(AU.toText(**res.1**));)

{"jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": ["0x02f84d058064646480800181c080a0cc3dbe377003569c916e6013cec9e2d3fec19e20d1b22149430a7a73950ae259a07aa55377d13d2d82165d411922caf5427efcd3d2762b5dedaf15490dc9af4843"], "id": 1}

would be failed.
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "rlp: expected input list for types.AccessList, decoding into (types.DynamicFeeTx).AccessList"
    }
}

**Comment by skilesare** [comment]
Any updates on this? Do we think the error is in the RLP encoder?

**Comment by av1ctor** [comment]
Fixed at commit 011be00
