### ISSUE TITLE
It is not possible to send larger amounts of Eth.

### ISSUE THREAD

**Issue by lazyanubis** [av1ctor/mo-evm-txs#2]
I noticed that the value type in the transaction is a 64-bit number, which seems to support a maximum of 18.xx Eth. Clearly, if someone wants to send more Eth, it would not be possible to do so.

Max Number(64bit)：18_446_744_073_709_551_615

1Eth = 10^18 Wei

**Comment by av1ctor** [comment]
Should be fixed now. Now values up to 2**256-1 (as in Ethereum) can be used.
