### ISSUE TITLE
[BUG] When I send 10000000000000000 Wei tokens, the actual transferred amount is only 152587890625 Wei.

### ISSUE THREAD

**Issue by lazyanubis** [av1ctor/mo-evm-txs#3]
When I send 10000000000000000 Wei tokens, the actual transferred amount is only 152587890625 Wei.

**Comment by av1ctor** [comment]
There was a bug when converting from little endian to big endian. Should be fixed now. Can you verify or provide a code snipped to test? Thanks

**Comment by lazyanubis** [comment]
I tried and succeeded. Thanks.
